baseURL: "https://alvinj404.github.io/" 
title: Yifan (Alvin) Jiang | 姜屹帆
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: Tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Teachings
          url: teachings/
          weight: 3
        - name: Tags
          url: tags/
          weight: 4
        - name: News
          url: news/
          weight: 5

params:
    description: "This website hosts Yifan Jiang's research papers, interests, and contact information."
    author: Yifan (Alvin) Jiang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yifan (Alvin) Jiang | 姜屹帆
          subtitle: "I am a <strong>MSCS student</strong> at the <strong><a href='https://www.cs.rochester.edu' target='_blank' rel='noopener'>University of Rochester</a></strong>, advised by <strong><a href='https://zhenbai.io/' target='_blank' rel='noopener'>Prof. Zhen Bai</a></strong> in the <strong><a href='https://interplaylab.com/' target='_blank' rel='noopener'>inter.play lab</a></strong>. I am also a part-time research assistant under <strong><a href='http://georgiejin.com/' target='_blank' rel='noopener'>Prof. Qiao Jin</a></strong> at <strong><a href='https://csc.ncsu.edu/' target='_blank' rel='noopener'>North Carolina State University</a></strong>. I am passionate about <strong>Human-Computer Interaction</strong>, <strong>AR/VR</strong>, <strong>EduTech</strong> and <strong>Computer Graphics</strong> and actively seeking Ph.D. opportunities in relevant areas."
          imageUrl: "headshot.png"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Publications
              url: publications/
            - name: Projects
              url: projects/
            - name: Teachings
              url: teachings/
            - name: Tags
              url: tags/
            - name: News
              url: news/

    socialIcons:
        - name: CV
          url: Yifan_Jiang_CV.pdf
        - name: Email
          url: mailto:yjiang54@ur.rochester.edu
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: Google Scholar
          url: https://google.com
        - name: GitHub
          url: https://github.com/AlvinJ404
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@alvinj6395
        - name: Twitter
          url: https://x.com/althegoat2001
        # - name: Bluesky
        #   url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yifan (Alvin) Jiang | 姜屹帆"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2